### ISSUE TITLE
Use Template as base, pull data from inputted Save file

### ISSUE THREAD

**Issue by tfitz237** [tfitz237/stardew#4]
Need to replace necessary IDs in new cabin

**Comment by eschwarz301** [comment]
I implemented using template as a base and asking the user to select a save file if they don't provide a path to one. Still have to figure out what elements must be replaced in the new cabin. So, half done.

**Comment by eschwarz301** [comment]
Closing this issue since it appears the game handles new character metadata discrepancies just fine.
